version: '3.8'

services:
  php:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    depends_on:
      - mysql

  symfony:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    depends_on:
      - php
    restart: always

  mysql:
    image: mariadb:10.4
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - "3386:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql:rw

  adminer:
    image: adminer
    depends_on:
      - mysql
    restart: always
